export const environment = {
  production: false,
  apiUrl: 'http://localhost:3000/api',
  authServiceUrl: 'http://localhost:3000/api/auths',
  crewServiceUrl: 'http://localhost:3000/api/crews',
  peopleServiceUrl: 'http://localhost:3000/api/people',
  skillsServiceUrl: 'http://localhost:3000/api/skills',
  equipmentServiceUrl: 'http://localhost:3000/api/equipment',
  inventoryServiceUrl: 'http://localhost:3000/api/inventory',
  supplierServiceUrl: 'http://localhost:3000/api/suppliers',
  fineServiceUrl: 'http://localhost:3000/api/fines',
  invoiceServiceUrl: 'http://localhost:3000/api/invoices',
  diggerServiceUrl: 'http://localhost:3000/api/diggers',
  usedequipmentServiceUrl:'http://localhost:3000/api/usedequipment',
  usedinventoryServiceUrl: 'http://localhost:3000/api/usedinventory',
  crewEmployeesServiceUrl: 'http://localhost:3000/api/crewemployees',
  routeServiceUrl: 'http://localhost:3000/api/routes',
  photoEvidenceServiceUrl: 'http://localhost:3000/api/photoevidence',
  necessaryPhasesServiceUrl:'http://localhost:3000/api/necessaryphases',
  contractUnitPhasesServiceUrl: 'http://localhost:3000/api/contractunitsphases',
  ticketStatusServiceUrl:'http://localhost:3000/api/ticketstatus'
};